server:
  port: 8086

spring:
  application:
    name: notification-service

  mail:
    host: smtp-mail.outlook.com
    username: 211452@astanait.edu.kz
    password: Aitu2021!!
    port: 587
    properties:
      mail.smtp.starttls.enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


application:
  config:
    url:
      authentication-service: http://localhost:8083/api/auth

telegram:
  name: dip_course_bot
  token: 6774831848:AAHLeX3JcOEmvKDpvR_FICLxAdKpg6-Lq8s