version: '3.3'

services:
  authentication-service:
    build: ./authentication-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
  course-service:
    build: ./course-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
  file-service:
    build: ./file-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
  quiz-service:
    build: ./quiz-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
