server:
  port: 8080

jwt:
  secret: 1T9wsI8ZppRATQeVmbq0QTGN4St4XG2r89N39Ar65QLEUesmSJ

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**

        - id: course
          uri: http://localhost:8081
          predicates:
            - Path=/api/course/**
          filters:
            - AuthenticationFilter

        - id: quiz
          uri: http://localhost:8082
          predicates:
            - Path=/api/quiz/**
          filters:
            - AuthenticationFilter

        - id: file
          uri: http://localhost:8084
          predicates:
            - Path=/api/files/**
          filters:
            - AuthenticationFilter


