server:
  port: 8084

spring:
  application:
    name: file-service
  datasource:
    username: postgres
    password: 7777
    url: jdbc:postgresql://localhost:5432/file_service
  jpa:
    hibernate:
      ddl-auto: update

minio:
  bucket: files
  url: https://play.min.io
  accessKey: Q3AM3UQ867SPQQA43P2F
  secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG