server:
  port: 8083

spring:
  application:
    name: authentication-service
  datasource:
    username: postgres
    password: 7777
    url: jdbc:postgresql://localhost:5432/authentication_service
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 1T9wsI8ZppRATQeVmbq0QTGN4St4XG2r89N39Ar65QLEUesmSJ
  lifetime: 24h
  refresh:
    lifetime: 48h

application:
  config:
    url:
      score-service: http://localhost:8085/api/score