server:
  port: 8082

spring:
  application:
    name: quiz-service
  datasource:
    username: postgres
    password: 7777
    url: jdbc:postgresql://localhost:5432/quiz_service
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
